name: Deploy

on:
  push:
    branches:
      - main

jobs:
  push-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: |
          pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
